name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Cypress Run
       uses: cypress-io/github-actions@v2
       with:
         build: npm run build
         start: npm start
      
